'use client';

import { ArrowUpRight, ArrowDown, Plus, Download } from 'lucide-react';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

const projects = [
  { title: 'Weaving the Storm', type: 'Physical model · Material exploration', image: 'page-9-0', description: 'A study of movement and volume through woven form. A series of physical explorations translates the energy of a storm into an open, three-dimensional structure.', images: ['page-9-0','page-9-1','page-10-0','page-10-1'], dark: true },
  { title: 'Two Hulls House', type: 'Architectural study · Drawing & model', image: 'page-6-2', description: 'An architectural study developed through plans, sections, elevations, and a physical model. The drawings examine the relationship between the house, its structure, and its site.', images: ['page-6-2','page-6-0','page-6-1','page-3-0','page-3-1','page-4-0','page-4-1','page-4-2','page-5-0','page-5-1'], dark: true },
  { title: 'Neon Nights', type: 'Depicting the Storm · Juried selection', image: 'page-8-0', description: 'From foundational sketches to the final depiction of a storm. “Neon Nights” was accepted to Terra Rosa Gallery’s “Wait Five Minutes” juried art show.', images: ['page-8-0','page-7-0','page-7-1','page-7-2'], dark: false },
  { title: 'Digital Landscapes', type: 'Rhino · Spatial studies', image: 'page-11-2', description: 'Digital work in Rhino exploring topography and built form through a rendered view, an isometric drawing, and a perspective section.', images: ['page-11-2','page-11-1','page-11-0'], dark: false },
  { title: 'Bruce Goff Abstract Model', type: 'Abstraction · Relief & model', image: 'page-2-1', description: 'An exploration of abstraction developed through a first relief and a final model, presented as part of Design I & II and Methods I & II coursework.', images: ['page-2-1','page-2-0'], dark: false },
  { title: 'Observations on Paper', type: 'Sketchbook · Hand drawing', image: 'page-12-0', description: 'A selection of hand-drawn studies. Sketching is an ongoing practice for developing a personal feel for design, proportion, and representation.', images: ['page-12-0','page-12-1','page-12-2'], dark: false },
];

export default function Home() {
 return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="navigation"><nav className="nav-inner" aria-label="Main navigation"><a href="#" className="wordmark">Cannon Gray<span className="wordmark-dot">.</span></a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="/documents/resume.pdf" target="_blank" rel="noreferrer">Resume <ArrowUpRight size={12}/></a><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={13}/></a></div></nav></header>
  <main id="main">
   <section className="hero container"><p className="eyebrow"><span className="status-dot"/> ARCHITECTURE STUDENT · UNIVERSITY OF OKLAHOMA</p><h1>Curiosity takes shape.</h1><div className="hero-bottom"><p>I’m Cannon Gray. Exploring the space between<br className="desktop-break"/> an idea, a drawing, and something real.</p><a className="text-link" href="#work">Explore my work <ArrowDown size={17}/></a></div>
   <a className="hero-image" href="#work" aria-label="Explore Cannon’s architectural work"><img src="/work/page-9-0.jpg" alt="Close-up of Cannon Gray’s intricate woven sculptural model, Weaving the Storm" fetchPriority="high"/><span className="image-caption"><span>Weaving the Storm</span><span>FORM, MATERIAL & MOVEMENT <ArrowUpRight size={17}/></span></span></a><div className="hero-footnote"><span>SELECTED WORK · DESIGN I & II / METHODS I & II</span><span>NORMAN, OKLAHOMA</span></div></section>
   <section className="work-section container" id="work"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, made tangible.</h2></div><a className="text-link" href="/documents/portfolio.pdf" target="_blank" rel="noreferrer">Full portfolio <ArrowUpRight size={17}/></a></div><div className="project-grid">{projects.map((project,i)=><Dialog key={project.title}><DialogTrigger className={`project-card ${project.dark?'dark-card':''}`}><div className="project-image"><img src={`/work/${project.image}.jpg`} alt={project.title} loading="lazy"/><span className="project-open"><Plus size={21}/></span></div><div className="project-caption"><div><p>{project.type}</p><h3>{project.title}</h3></div><span className="project-number">0{i+1}</span></div></DialogTrigger><DialogContent className="project-dialog"><div className="dialog-intro"><p className="eyebrow">{project.type}</p><DialogTitle className="dialog-title">{project.title}</DialogTitle><DialogDescription className="dialog-description">{project.description}</DialogDescription></div><div className="dialog-gallery">{project.images.map((img,j)=><img key={img} src={`/work/${img}.jpg`} alt={`${project.title} — study ${j+1}`} loading="lazy"/>)}</div><a className="text-link" href="/documents/portfolio.pdf" target="_blank" rel="noreferrer">View original portfolio <ArrowUpRight size={16}/></a></DialogContent></Dialog>)}</div></section>
   <section id="about" className="about-section"><div className="container about-grid"><div><p className="eyebrow">02 / A LITTLE ABOUT ME</p><h2>A student of space.<br/><span>Always a work<br/>in progress.</span></h2></div><div className="about-copy"><p>I’m studying architecture at the University of Oklahoma, building a foundation in design through drawing, digital modeling, and hands-on making.</p><p>I enjoy sketching to develop my eye and design style. Away from the studio, you’ll find me at an OU football game with friends and family, or listening to the music that keeps my ideas moving.</p><div className="skill-list">{['Rhino 8','3D & plan-view modeling','Adobe Photoshop','Adobe Illustrator','Sketching','Physical model making'].map(s=><span key={s}>{s}</span>)}</div><a className="text-link" href="/documents/resume.pdf" download="Cannon-Gray-Resume.pdf">Download resume <Download size={16}/></a></div></div></section>
   <section className="resume-section container"><div className="resume-column"><p className="eyebrow">EDUCATION</p><article className="resume-item"><p className="date">CLASS OF 2030</p><h3>University of Oklahoma</h3><p>Bachelor of Architecture · 3.88 GPA</p><p className="detail">Oklahoma Rising Scholars Award recipient</p></article><article className="resume-item"><p className="date">CLASS OF 2025</p><h3>Verdigris High School</h3><p>4.00 GPA · 35 ACT</p><p className="detail">Oklahoma Foundation for Excellence Academic All Stater. NHS chapter vice president and football team captain.</p></article></div><div className="resume-column"><p className="eyebrow">EXPERIENCE</p><article className="resume-item"><p className="date">SEPTEMBER 2025 — PRESENT</p><h3>University of Oklahoma Recreation Center</h3><p>Facilities Maintenance Worker · Norman, OK</p><p className="detail">Maintaining university recreation spaces, from sports fields to weight rooms, with reliability across early shifts and all weather conditions.</p></article><article className="resume-item"><p className="date">JUNE — AUGUST 2026</p><h3>Oklahoma Air National Guard</h3><p>Facilities Assistant · Tulsa, OK</p><p className="detail">Hands-on facilities maintenance, using tools and practical problem-solving through demanding summer conditions.</p></article></div></section>
   <section className="contact-section" id="contact"><div className="container"><p className="eyebrow">03 / GET IN TOUCH</p><h2>Good things start<br/>with a conversation.</h2><a className="contact-email" href="mailto:9.cannon.gray@gmail.com">9.cannon.gray@gmail.com <ArrowUpRight/></a><p>For opportunities, collaborations, or a simple hello.</p></div></section>
  </main><footer className="container"><a className="wordmark" href="#">Cannon Gray.</a><p>Architecture & exploration.</p><a href="#">Back to top ↑</a></footer>
 </>;
}
